#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: "ir-norn.github.io"

# Short bio or description (displayed in the header)
description: scripting

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: nil
  email: _@co.jp
  facebook: nil
  flickr: nil
  github: ir-norn
  instagram: nil
  linkedin: nil
  pinterest: nil
  rss: nil # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: ir_norn_
  stackoverflow: nil # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: nil # channel/<your_long_string> or user/<user-name>
  googleplus: nil # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: ir-norn

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: "UA-68496450-1"

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "http://ir-norn.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/ir-norn.github.io"

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
#highlighter: rouge
#permalink: /:title/
permalink: /blog/:categories/:title


# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
# --sstyle compact compressed nested expanded
sass:
  style: :nested # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME


# --------------------------
script:
    module1: true
    module2: false
#{% if site.script.module1 %}a{% endif %}
#{% if site.script.module2 %}b{% endif %}

